dist: trusty
language: node_js
bundler_args: "--retry 0"

node_js:
  - '6.10'

env:
  - SAUCE_USERNAME=jasmine-boilerplate

addons:
  jwt:
    secure: PIA+bwbcthpN09AG2G8Wda3lvfgxppVq9e8JUCZaxJdAyegsV6oTuHORY2f4xwhcXB3HErlzrbUz74fyR/T4KaTREE+rQNtV6ZWBBhCLJr4UTGeNwEpQnVWwd3tGD+0Z8GQt2QfnYMdRHOB+YkY27q3j2fTvAPXQzVQ6nPUR7NY6VnGSB3561pncJqYRDI0Esx8c686jPDauPWI5J9x8aJIHDmHrx//aB4RHhumKWFUD5KBbpx9mAcm3PN3Iw8q3mPnsoAOA0q4u743jjv2FRkSLLhL/VY/jtoGKYebZpp/Rszb+PAhQKf9G2kQbY8ghUsp6pDUAFYho2m841AXO10NLSEM+MjXXtNg1WgPda3aSGuwIQgXaxyPrmSIVLcKZUgLrnChj3zAAzGg2H1Ijaq8r92nBKbxLZ4cw7ephtnHRoZ9feMnwc3tRlPrAwTMy5VxCf0DgZaGXwPIpVkpatnacROsHT4rxhdtlChw401DKK1/pVmSWIJoJOrAQ6oxEPjywcV+ov6yhaXJ9ye6qHMLde/LMgCiv0tk6I4pl9WIe5xATaUDjEMhS43XU83m7lW624bDhuJLibJmV6kgDqZjyP2z5NjtS3hQSaeh1v29bLto+mo8BduL047XBZW3WOvM4kTooRDCEZyS5i1wmjXv5keUopV/F/CgbPBnGB9I=
